name: Ruby CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        rvm:
          - 2.6.6
          - 2.7.8
          - 3.2.8
        gemfile:
          - gemfiles/rails42.gemfile
          

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.rvm }}

    - name: Install Bundler
      run: gem install bundler

    - name: Install dependencies
      run: |
        bundle config path vendor/bundle
        bundle install

    - name: Prepare database
      run: bundle exec rake db:prepare

    - name: Run tests
      run: bundle exec rake
